/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

 

Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
 */

findTheDifference = function(s, t) {
    const map = {}
    for(const letter of s){
        map[letter ] = (map[letter ] | 0) + 1
    }
    for(const char of t){
        if(!map[char]){
            return char
        }
        map[char]--
    }
};